### ISSUE TITLE
SEEED STUDIO XIAO NRF52840 compatible

### ISSUE THREAD

**Issue by tamccauley** [ajs123/KBikeBLE#14]
Just an FYI....
I got KBikeBLE's software to work with a SEEED STUDIO XIAO NRF52840 processor, which is quite a bit smaller and less expensive.  A few changes I had to make:
Added “static const uint8_t VBAT  = PIN_VBAT ;” to Variant.h file so I could use this in bike_interface.h.
In Bike_interface.h, instead of #define BATTERY_PIN A6, changed to #define BATTERY_PIN VBAT  
In Arduino IDE, in board manager, added “Seeed nRF52 by Seeed Studio.

I used 1.0.0 of this board library as I believe newer versions don't support the BLE libraries in this project.

**Comment by ajs123** [comment]
Thanks. This is good to know. I've noted it in the HOWTO.
