### ISSUE TITLE
Stuck on log screen when FTMS enabled

### ISSUE THREAD

**Issue by ajk1982** [ajs123/KBikeBLE#16]
I would like to try BitGym which I believe requires FTMS. When I enable FTMS by uncommenting #define PROVIDE_FTMS in options.h, it freezes on the log screen during startup. 
![IMG_5676](https://user-images.githubusercontent.com/1137677/215330010-bfb09d5f-aaff-4492-bfb1-8cc3cbdbbe0d.JPG)

**Comment by ajs123** [comment]
Hmmm... First question: Does bluetooth start (does the blue LED begin
flashing?)

**Comment by antknight** [comment]
No, no connection via bluetooth possible.

**Comment by ajs123** [comment]
I'm not in a good position to try to replicate on this end. Would you be
able to try release v1.1 instead of main?

**Comment by antknight** [comment]
I can confirm v1.1 works and is detected by BitGym!

**Comment by ajs123** [comment]
Thanks. I added a note in the README about this being an issue in the main branch and added the fix to the TODO.
