### ISSUE TITLE
Calibration tool 3D model

### ISSUE THREAD

**Issue by ajk1982** [ajs123/KBikeBLE#17]
I modelled a calibration tool for those with 3D printers. Dimensions taken from a genuine Keiser tool. Model available here:

[thangs.com](https://thangs.com/designer/MacGyver1982/3d-model/Keiser%20M3%20calibration%20tool-686222) or [printables.com](https://www.printables.com/model/387199)

**Comment by ajs123** [comment]
Thanks! I added a link to this issue in the HOWTO (calibration section).
