### ISSUE TITLE
Setting #define GEAR_DISPLAY false, uses GEAR label on startup

### ISSUE THREAD

**Issue by ajk1982** [ajs123/KBikeBLE#18]
If setting #define GEAR_DISPLAY false in options.h, on startup the label GEAR rather than RES % is used. Toggles correctly when moving resistance lever to the top.

**Comment by ajs123** [comment]
Please try the KBikeBLE.ino as edited a few minutes ago. The fix is at line 160.  UNTESTED but should do it. Thanks for catching and reporting this.

**Comment by ajk1982** [comment]
Works perfectly, thanks!
