### ISSUE TITLE
My grain of sand. 3D print

### ISSUE THREAD

**Issue by serbasan** [ajs123/KBikeBLE#19]
I am very grateful for the work on this project. I have assembled everything and it is going very well. Better than the original screen.
I have designed a quick box to house all the electronics and have mentioned this project.
I don't know if I'm breaking any rules. If so, let me know.
And if a larger screen with more information is added in the future, I would design another box.
Thank you so much.
Link to box:
[Box 3D](https://www.thingiverse.com/thing:6318006/files)

**Comment by ajs123** [comment]
Thanks! I've added a link to the README.
